### ISSUE TITLE
SyntaxError: Invalid or unexpected token => @charset "UTF-8";

### ISSUE THREAD

**Issue by bluemix** [AT-UI/at-ui#54]
I am using [Nuxt.js](https://nuxtjs.org/), and used its boilerplate to build the Nuxt.js template.
This is the problem I am getting after importing `import 'at-ui-style'` code.

```
nuxt:render Rendering url / +3m
[vue-router] Failed to resolve async component default: SyntaxError: Invalid or unexpected token
[vue-router] uncaught error during route navigation:
/Users/bluemix/Odoo_OpendEduCat/auc_nuxtjs/node_modules/at-ui-style/css/at.css:1
(function (exports, require, module, __filename, __dirname) { @charset "UTF-8";
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at r (/Users/bluemix/Odoo_OpendEduCat/auc_nuxtjs/node_modules/vue-server-renderer/build.js:7758:16)
    at Object.<anonymous> (server-bundle.js:3839:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.68 (pages/index.4d0ebf856b8182389e7a.js:85:70)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.62 (pages/index.4d0ebf856b8182389e7a.js:9:288)
    at __webpack_require__ (server-bundle.js:27:30)
```

and thanks for your great project 🙂

**Comment by koppthe** [comment]
Try to use global css in Nuxt.js
https://github.com/nuxt/nuxt.js/blob/master/examples/global-css/nuxt.config.js
https://nuxtjs.org/api/configuration-css

**Comment by bluemix** [comment]
I've set this config in `nuxt.config.js`,

```
  css: [
    // Load a node module directly (here it's a SASS file)
    'at-ui-style',
    // CSS file in the project
    '@/assets/css/main.css',
    // SCSS file in the project
    '@/assets/css/main.scss'
  ]
```
and got this,

```
 ERROR  Failed to compile with 2 errors                                                                                                                             

These relative modules were not found:

* ../assets/css/main.css in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["/Users/bluemix/Odoo_OpendEduCat/auc_nuxtjs/node_modules/babel-preset-vue-app/dist/index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./.nuxt/App.vue
* ../assets/css/main.scss in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["/Users/bluemix/Odoo_OpendEduCat/auc_nuxtjs/node_modules/babel-preset-vue-app/dist/index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./.nuxt/App.vue
```

**Comment by koppthe** [comment]
it seem that `main.css` and `main.scss` are not in your relative path.

**Comment by bluemix** [comment]
and the solution? :)

**Comment by bluemix** [comment]
here is the full `nuxt.config.js` file,
```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'aux_nuxtjs',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'AUC Odoo' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** Run ESLint on save
    */
    extractCSS: true,
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  },
  css: [
    // Load a node module directly (here it's a SASS file)
    'at-ui-style',
    // CSS file in the project
    '@/assets/css/main.css',
    // SCSS file in the project
    '@/assets/css/main.scss'
  ]
}
```

**Comment by koppthe** [comment]
I try to initialize a nuxt project with the command below:
```bash
vue init nuxt-community/starter-template nuxt-demo
```
and then install `at-ui` and `at-ui-style`
```bash
yarn add at-ui
yarn add at-ui-style
```
set the css config in `nuxt.config.js`
```js
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'nuxt-demo',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  /*
  ** Customize the progress bar color
  */
  loading: { color: '#3B8070' },
  /*
  ** Build configuration
  */
  css: [
    'at-ui-style'
  ],
  build: {
    extractCSS: true,
    /*
    ** Run ESLint on save
    */
    extend (config, ctx) {
      if (ctx.dev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}

```
use the components of `at-ui` in `pages/index.vue`
```js
<template>
  <section class="container">
    <div>
      <logo/>
      <h1 class="title">
        nuxt-demo
      </h1>
      <h2 class="subtitle">
        Nuxt.js project
      </h2>
      <div class="links">
        <a href="https://nuxtjs.org/" target="_blank" class="button--green">Documentation</a>
        <a href="https://github.com/nuxt/nuxt.js" target="_blank" class="button--grey">GitHub</a>
      </div>
      <at-button @click="showMessage">Test</at-button>
    </div>
  </section>
</template>

<script>
import Vue from 'vue'
import Logo from '~/components/Logo.vue'
import AtComponents from 'at-ui'

Vue.use(AtComponents)

...
```

It works~

**Comment by bluemix** [comment]
now it works 👍 
thanks a lot @koppthe
